"""add fields to ticket

Revision ID: 6415ff59f43d
Revises: 
Create Date: 2025-09-27 15:50:34.557018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6415ff59f43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('expire_time', sa.DateTime(), nullable=False))
    op.add_column('tickets', sa.Column('state', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'state')
    op.drop_column('tickets', 'expire_time')
    # ### end Alembic commands ###
